require('es6-promise').Promise;

module.exports = {
    CMS_CONTENT_URL :'http://localhost:7777/jsons/agentDashboard.json',   // "http://localhost:7777/jsons/CMSResponseStub.json',
    CMS_DASHBOARD_CONTENT_SUCCESS : 'CMS_DASHBOARD_CONTENT_SUCCESS',
    //USER_DETAIL_FETCH_SUCCESS : 'ON_STUB_FETCH',
    REQUEST_DASHBOARD_STATE_UPDATE : 'REQUEST_DASHBOARD_STATE_UPDATE',
    RESET_APP_STATE : 'RESET_APP_STATE',
    SUMMARY_DASHBOARD_CONTENT_SUCCESS :'SUMMARY_DASHBOARD_CONTENT_SUCCESS',
    SUMMARY_ASSISTANT_CONTENT_SUCCESS :'SUMMARY_ASSISTANT_CONTENT_SUCCESS',
    SUMMARY_DASHBOARD_CONTENT_SUCCESS_ASSISTANT:'SUMMARY_DASHBOARD_CONTENT_SUCCESS_ASSISTANT'
}
