require('es6-promise').Promise;

module.exports = {
    ON_DEMOGRAPHIC_CONTENT_SUCCESS : 'ON_DEMOGRAPHIC_CONTENT_SUCCESS',
    REQUEST_STATE_UPDATE : 'REQUEST_DEMOGRAPHIC_STATE_UPDATE',
    RESET_APP_STATE : 'RESET_APP_STATE',
    SAVE_DATA_IN_STATE : 'SAVE_DATA_IN_STATE'
}
