require('es6-promise').Promise;

module.exports = {
    ON_LOGIN_CONTENT_FETCH: 'ON_LOGIN_CONTENT_FETCH',
    REQUEST_STATE_LOGIN_UPDATE: 'REQUEST_STATE_LOGIN_UPDATE',
    ON_LOGIN_STUB_FETCH: 'ON_LOGIN_STUB_FETCH',
    CMS_CONTENT_LOGIN_SUCCESS: 'CMS_CONTENT_LOGIN_SUCCESS'
}
