module.exports = {
        REQUEST_SELECTPLAN_STATE_UPDATE : "REQUEST_SELECTPLAN_STATE_UPDATE",
        RESET_SELECTPLAN_COMPONENT_STATE: "RESET_SELECTPLAN_COMPONENT_STATE",
        REQUEST_SELECTPLAN_DATA         : "REQUEST_SELECTPLAN_DATA"
}
