require('es6-promise').Promise;

module.exports = {
    ON_DISCLAIMER_CONTENT_SUCCESS : 'ON_DISCLAIMER_CONTENT_SUCCESS',
    REQUEST_DISCLAIMER_STATE_UPDATE : 'REQUEST_DISCLAIMER_STATE_UPDATE',
    RESET_APP_STATE :'RESET_APP_STATE'
}
